name: CI with gtest and lcov

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
 build:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Adding gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest

  - name: Install cpp-coveralls
    run: pip install cpp-coveralls

  - name: Config banking with tests
    run: cmake -H. -B${{github.workspace}}/build -DBUILD_TESTS=ON -DCODE_COVERAGE=ON

  - name: Build banking
    run: cmake --build ${{github.workspace}}/build

  - name: Run tests
    run: build/check --enable-gcov

  - name: Measure coverage
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    run: coveralls -r build

